In [1]:
! pip install pandas numpy


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("XOR_Dataset.csv")

X = data[['X', 'Y']].values
y = data[['Z']].values

print(X)
print(y)

[[0 0]
 [0 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]
[[0]
 [1]
 [0]
 ...
 [0]
 [0]
 [0]]


In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [5]:
np.random.seed(42)

input_neurons = 2
hidden_neurons = 2
output_neurons = 1

W1 = np.random.rand(input_neurons, hidden_neurons)
W2 = np.random.rand(hidden_neurons, output_neurons)

b1 = np.random.rand(1, hidden_neurons)
b2 = np.random.rand(1, output_neurons)

print("W1:", W1)
print("W2:", W2)
print("b1:", b1)
print("b2:", b2)

W1: [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]
W2: [[0.15601864]
 [0.15599452]]
b1: [[0.05808361 0.86617615]]
b2: [[0.60111501]]


In [6]:
def forward(X):
    global z1, a1, z2, a2
    
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    
    return a2

In [7]:
def backward(X, y, output, learning_rate):
    global W1, W2, b1, b2
    
    error = y - output
    d_output = error * sigmoid_derivative(output)
    
    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(a1)
    
    W2 += a1.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    
    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

In [8]:
epochs = 14500
learning_rate = 0.001

for i in range(epochs):
    output = forward(X)
    backward(X, y, output, learning_rate)
    
    if i % 1000 == 0:
        loss = np.mean(np.square(y - output))
        print(f"Epoch {i}, Loss: {loss}")

Epoch 0, Loss: 0.28619735506826
Epoch 1000, Loss: 0.0007280039634271512
Epoch 2000, Loss: 0.00030333705009284213
Epoch 3000, Loss: 0.00018964029379510061
Epoch 4000, Loss: 0.00013742532286547228
Epoch 5000, Loss: 0.00010755468584735715
Epoch 6000, Loss: 8.825354205089723e-05
Epoch 7000, Loss: 7.477219685109076e-05
Epoch 8000, Loss: 6.483153877344441e-05
Epoch 9000, Loss: 5.720309069523176e-05
Epoch 10000, Loss: 5.116678783278685e-05
Epoch 11000, Loss: 4.627290849808972e-05
Epoch 12000, Loss: 4.222622701423952e-05
Epoch 13000, Loss: 3.882499109583778e-05
Epoch 14000, Loss: 3.592668292272415e-05


In [9]:
print("\n========== XOR_GATE ==========")
print("Final Predictions Approximately:")
print(output)


========== XOR_GATE ==========
Final Predictions Approximately:
[[0.00670956]
 [0.99443146]
 [0.00566962]
 ...
 [0.00566962]
 [0.00566962]
 [0.00566962]]


In [ ]:
test = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

print("Test Output Approximately:\n", forward(test))

Test Output Approximately:
 [[0.00670932]
 [0.99443166]
 [0.99445307]
 [0.00566942]]
